version: "3.8"

services:
  safe-stremio:
    image: psyb0t/safe-stremio:latest
    cap_add:
      - NET_ADMIN
    environment:
      - WITH_OPENVPN=true
      - USERNAME=user
      - PASSWORD=pass
    ports:
      - "8080:80"
    volumes:
      - ./openvpn/config.ovpn:/vpn-config.ovpn
      - ./openvpn/auth.txt:/vpn-auth.txt
    restart: unless-stopped

  streamio:
    image: stremio/server:latest
    container_name: streamio
    volumes:
      - ./stremio:/root/.stremio-server
    ports:
      - 11470:11470
      - 12470:12470
    depends_on:
      - safe-stremio
    restart: unless-stopped
